### ISSUE TITLE
Register Computor per DM

### ISSUE THREAD

**Issue by Dudenicks** [Qubic-World/computor-poll-bot#1]
I have read that it is possible to let a bot receive DM from users. Is it possible to make the pollbot receive register messages per direct message? I think this is an important issue because due to privacy reasons a lot of Computors might not register at all. If it is not technically necessary to publicise all your IDs they should be treated as personal and private information. Anonymity is hardly possible with Discord, which is another matter, but please if possible make at least the registration process kind of private.

**Comment by N-010** [comment]
When I have time, I'll do it

**Comment by N-010** [comment]
Done
